#pragma config(Sensor, in1,    marbleColorSensor, sensorLineFollower)
#pragma config(Motor,  port1,           shooter,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          dispenser,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Light blue
const int aLower = 2400; //TODO
const int aUpper = 2600; //TODO

// Green
const int bLower = 2200; //TODO
const int bUpper = 2400; //TODO

// White
const int cLower = 0; //TODO
const int cUpper = 1300; //TODO

int getMarbleColor() {
	return SensorValue[marbleColorSensor];
}

bool marblePresent() {
	int color = getMarbleColor();
	return (aLower < color && color < aUpper) || (bLower < color && color < bUpper) || (cLower < color && color < cUpper);
}

void dispense() {
	motor[dispenser] = 10; //TODO maybe change
	while (marblePresent()) {}
	while (!marblePresent()) {}
	motor[dispenser] = 0;
}

const int lowSpeed = -40; //TODO
const int medSpeed = -80; //TODO
const int highSpeed = -127; //TODO

task main() {
	for (;;) {
		if (marblePresent()) {
			int color = getMarbleColor();
			delay(500);
			if (aLower < color && color < aUpper) {
				motor[shooter] = highSpeed;
			} else if (bLower < color && color < bUpper) {
				motor[shooter] = medSpeed;
			} else if (cLower < color && color < cUpper) {
				motor[shooter] = lowSpeed;
			}
		}
		dispense();
	}
}
