#pragma config(Sensor, in1,    marbleColorSensor, sensorLineFollower)
#pragma config(Motor,  port1,           shooter,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          dispenser,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int aLower = 0; //TODO
const int aUpper = 0; //TODO
const int bLower = 0; //TODO
const int bUpper = 0; //TODO
const int cLower = 0; //TODO
const int cUpper = 0; //TODO

int getMarbleColor() {
	return SensorValue[marbleColorSensor];
}

bool marblePresent() {
	int color = getMarbleColor();
	return (aLower < color && color < aUpper) || (bLower < color && color < bUpper) || (cLower < color && color < cUpper);
}

void dispense() {
	motor[dispenser] = 15; //TODO maybe change
	while (marblePresent()) {}
	while (!marblePresent()) {}
	motor[dispenser] = 0;
}

const int lowSpeed = 0; //TODO
const int medSpeed = 0; //TODO
const int highSpeed = 0; //TODO

task main() {
	for (;;) {
		if (marblePresent()) {
			int color = getMarbleColor();
			if (aLower < color && color < aUpper) {
				motor[shooter] = highSpeed;
			} else if (bLower < color && color < bUpper) {
				motor[shooter] = medSpeed;
			} else if (cLower < color && color < cUpper) {
				motor[shooter] = lowSpeed;
			}
		}
		dispense();
		// Maybe add delay here
	}
}
